### ISSUE TITLE
Feat : Create assignment services, routes and controller.

### ISSUE THREAD

**Issue by aialok** [houseofgeeks/hgv2#69]
**Feature**: 🛠️ Implement Assignment : Services, Routes, and Controller

**Description:**
Create assignment services, routes, and controller for the application to facilitate the management of assignments. This will involve developing backend functionalities for handling assignment creation, updating, deletion, and retrieval through appropriate service methods. Additionally, design and implement API routes to expose these functionalities, ensuring proper request handling and validation. Finally, develop a controller to orchestrate interactions between the routes and services, ensuring seamless integration and functionality within the application.

**Comment by irfan-iiitr** [comment]
@aialok  Check- [42a890a](https://github.com/houseofgeeks/hgv2/pull/70/commits/42a890a3cf80128a9775820333cfc214cd874566)
